### ISSUE TITLE
Update dependencies on idp-hook-updates

### ISSUE THREAD

**Issue by rhofschn** [cisco-sbgidm/idp-hook-updates#434]
Updates have caused some breakage, so review CI logs and correct.

**Comment by rhofschn** [comment]
Hey @vvlasi – thought this might be a quick fix I could address without setting up a local environment, becoming more familiar with Typescript, node-redis, etc. – but that's not the case. Assigning to you.

**Comment by rhofschn** [comment]
Use my blind experiments on https://github.com/cisco-sbgidm/idp-hook-updates/pull/433 for clues.

**Comment by vvlasi** [comment]
Resolved all PRs created by dependabot.
