### ISSUE TITLE
Move this project to Open Source

### ISSUE THREAD

**Issue by Didithekli** [cisco-sbgidm/idp-hook-updates#82]
We got permissions to publish now we need to follow these [Instructions ](https://developer.cisco.com/codeexchange/github/submit) from @eckelcu to make it public.

**Comment by odedpeer** [comment]
Converted the repo to public and submitted to devnet.
Will work on a blog post.

**Comment by odedpeer** [comment]
Waiting on approval for the blog post, but the code is already open
